---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:1.12.14-alpine3.10
    environment:
      GOPROXY: https://athens.chuhlomin.com
    commands:
      - apk add --no-cache make git gcc libc-dev protobuf
      - make test
      - make install

  - name: cr-latest
    image: plugins/docker
    settings:
      repo: chuhlomin/protoc-gen-bq-schema
      username: chuhlomin
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_COMMIT:0:7}
        - latest
    when:
      event:
        - push
      branch:
        - develop

  - name: cr-release
    image: plugins/docker
    settings:
      repo: chuhlomin/protoc-gen-bq-schema
      username: chuhlomin
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_TAG}
    when:
      event:
        - tag

trigger:
  event:
    - push
    - tag
