---
kind: pipeline
type: docker
name: default

steps:
  - name: cr
    image: plugins/docker
    settings:
      username: chuhlomin
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_COMMIT}
        - latest
    when:
      event: push
      branch: master

trigger:
  branch:
    - master

image_pull_secrets:
  - dockerconfigjson
