---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.12.14-alpine3.10
    environment:
      GOPROXY: https://athens.chuhlomin.com
    commands:
      - apk add --no-cache make git gcc libc-dev protobuf
      - make test
      - make install
    when:
      event: push

  - name: cr
    image: plugins/docker
    settings:
      username: chuhlomin
      password:
        from_secret: docker_password
      tags:
        - latest
        - ${DRONE_COMMIT:0:7}
    when:
      event: push
      branch: develop

trigger:
  branch:
    - develop

image_pull_secrets:
  - dockerconfigjson
